// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:codepenFill': typeof import('virtual:vite-icons/akar-icons/codepen-fill')['default']
    'AkarIcons:dribbbleFill': typeof import('virtual:vite-icons/akar-icons/dribbble-fill')['default']
    'AkarIcons:instagramFill': typeof import('virtual:vite-icons/akar-icons/instagram-fill')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AngularIcon: typeof import('./src/components/AngularIcon.vue')['default']
    'AntDesign:heartFilled': typeof import('virtual:vite-icons/ant-design/heart-filled')['default']
    BlurhashImg: typeof import('./src/components/BlurhashImg.vue')['default']
    Charts: typeof import('./src/components/Charts.vue')['default']
    CodeCopy: typeof import('./src/components/CodeCopy.vue')['default']
    ColorPalette: typeof import('./src/components/ColorPalette.vue')['default']
    ElasticSearchLogo: typeof import('./src/components/ElasticSearchLogo.vue')['default']
    'Eva:colorPaletteFill': typeof import('virtual:vite-icons/eva/color-palette-fill')['default']
    'Eva:githubOutline': typeof import('virtual:vite-icons/eva/github-outline')['default']
    'Eva:linkedinOutline': typeof import('virtual:vite-icons/eva/linkedin-outline')['default']
    EvaTwitterOutline: typeof import('virtual:vite-icons/eva/twitter-outline')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FunConsole: typeof import('./src/components/FunConsole.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'IconParkOutline:sunOne': typeof import('virtual:vite-icons/icon-park-outline/sun-one')['default']
    'Il:moon': typeof import('virtual:vite-icons/il/moon')['default']
    Languages: typeof import('./src/components/Languages.vue')['default']
    LanguagesBad: typeof import('./src/components/LanguagesBad.vue')['default']
    LanguagesBreakdown: typeof import('./src/components/LanguagesBreakdown.vue')['default']
    LazyImage: typeof import('./src/components/LazyImage.vue')['default']
    'Noto:laptop': typeof import('virtual:vite-icons/noto/laptop')['default']
    'Noto:octopus': typeof import('virtual:vite-icons/noto/octopus')['default']
    'Noto:rolledUpNewspaper': typeof import('virtual:vite-icons/noto/rolled-up-newspaper')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    PostsList: typeof import('./src/components/PostsList.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    ProjectsList: typeof import('./src/components/ProjectsList.vue')['default']
    Reactions: typeof import('./src/components/Reactions.vue')['default']
    SiteMapComponent: typeof import('./src/components/SiteMapComponent.vue')['default']
    Tags: typeof import('./src/components/Tags.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TimelineComponent: typeof import('./src/components/TimelineComponent.vue')['default']
    ViewMore: typeof import('./src/components/ViewMore.vue')['default']
  }
}

export { }
